### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by oleorhagen** [cfengine/cfbs#162]
With the hard-coded `git tag` extraction in `setup.py` it is not possible to build this package from source.

I ran into this as I was packaging the tool.

Suggested fix: Hard-code the version for releases

**Comment by olehermanse** [comment]
I don't think we will do this (the current setup is way easier and less error-prone to maintain). But we can look into generating a source tarball which has the version number in it.

**Comment by olehermanse** [comment]
@oleorhagen how did you try building from source?

**Comment by oleorhagen** [comment]
> @oleorhagen how did you try building from source?

I was trying to package it for `arch linux` which prefers it from source. 

So I took the published source tarbasll from `pypi`, and it won't build because of this

**Comment by oleorhagen** [comment]
Just download the release, and `setup.py` will fail obvs

**Comment by olehermanse** [comment]
@oleorhagen building from source will work if you clone the repo with tags.

We can look into generating a ready to build source tarball, shouldn't be very difficult.

**Comment by oleorhagen** [comment]
> @oleorhagen building from source will work if you clone the repo with tags.
> 
> We can look into generating a ready to build source tarball, shouldn't be very difficult.

Yes, it's what I wound up doing. Just wanted to point out that ur source tarballs are not working as intended
